import Layout from "./layout"
import Hero from "./Hero"
import About from "./About"
import Projects from "./Projects"
import Survey from "./Survey"
import Slider from "./Slider"
import Algolia from "./Algolia"
import GridProjects from "./GridProjects"
import Wallpaper from "./Wallpaper"
import Hero1 from "./Hero1"
import About1 from "./About1"
export { Layout, Hero, About, Projects, Survey, Slider, Algolia, GridProjects,Wallpaper ,Hero1,About1}
